aplikacja_do_pracy/urls.py
from django.contrib import admin
from django.urls import path, include
from do_pracy import views


urlpatterns = [
    path("do_pracy/", include("do_pracy.urls")),
    path("admin/", admin.site.urls),
    path("", views.IndexView.as_view(), name="welcome"),
]

do_pracy/urls.py
from django.urls import path
from .views import HomeView, RecordView
from django.conf import settings
from django.conf.urls.static import static


app_name = "do_pracy"
urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("record", RecordView.as_view(), name="record"),
]

do_pracy/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    file = models.CharField(max_length=200)
    profile_photo = models.CharField(max_length=200)

    def __str__(self):
        return self.first_name

do_pracy/forms.py
from django import forms
from do_pracy.models import Post


class HomeForm(forms.ModelForm):
    first_name = forms.CharField(required=True)

    class Meta:
        model = Post
        fields = ("first_name", "last_name", "file", "profile_photo")

do_pracy/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from do_pracy.forms import HomeForm
from .models import Post


class HomeView(TemplateView):
    template_name = "base.html"

    def get(self, request):
        form = HomeForm()
        posts = Post.objects.all()
        args = {"form": form, "posts": posts}

        return render(request, self.template_name, args)

    def post(self, request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            return HttpResponseRedirect("record")


class RecordView(TemplateView):
    template_name = "do_pracy/record.html"

    def get(self, request):
        posts = Post.objects.all()

        for post in posts:
            first_name = post.first_name
            last_name = post.last_name
            date = post.date
            file = post.file
            photo_link = post.profile_photo[:-1].rpartition("/")

        args = {
            "posts": posts,
            "photo_link": photo_link[0],
            "first_name": first_name,
            "last_name": last_name,
            "date": date,
            "file": file,
        }

        return render(request, self.template_name, args)


class IndexView(TemplateView):
    template_name = "welcome.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["latest_articles"] = Post.objects.all()[:5]

        return context

do_pracy/templates/do_pracy/index.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rekra!</title>
      <link rel="stylesheet" href="https://uplycdn.com/widget/dqupyrgsJwQu/app.a732548d.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>


<!-- head of frontend welcome site -->
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Rekra
      </h1>
      <h2 class="subtitle">
        Please enter your data
      </h2>
    </div>
  </div>
</section>
<div class="tabs is-fullwidth is-boxed is-widescreen">
  <ul>
    <li><div>
    <a href="https://github.com/codemangasior" class="nav-item">
        <span class="icon">
            <i class="fa fa-github fa-2x"></i>
        <label class="label">codemangasior</label>
        </span>
    </a>
    </div></li>
    <li><div>
    <a href="mailto:lukasz.gasiorowski92@gmail.com" class="nav-item">
        <span class="icon">
            <i class="fa fa-at fa-2x"></i>
        <label class="label">codemangasior</label>
        </span>
    </a>
    </div></li>
  </ul>
</div>
    <div class="container">
          <div class="box">
                {% block welcome %}
                {% endblock %}
          </div>
    </div>
      <script src="https://uplycdn.com/widget/Yu922Xq6RDLZ/app.30a67353.js"></script>
  </body>
</html>

do_pracy/templates/do_pracy/record.html
{% extends 'base.html' %}

{% block content %}
    <div class="box">
        <p class="title is-5">This is your data</p>
            <div class="notification">
                <div>
                    <div>
                        <img src="{{ photo_link }}/avatar:200/">
                    </div>
                        <label class="label">
                            First name: {{ first_name }}
                        </label>
                        <label class="label">
                            Last name: {{ last_name }}
                        </label>
                        <label class="label">
                            Download:
                            <a href="{{ file }}">CV</a>
                        </label>
                        <label class="label">
                            added {{ date|date:'d/m/Y'}} at {{ date|date:'H:i' }}
                        </label>
                </div>
            </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rekra!</title>
      <link rel="stylesheet" href="https://uplycdn.com/widget/dqupyrgsJwQu/app.a732548d.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>

<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Rekra
      </h1>
      <h2 class="subtitle">
        Please enter your data
      </h2>
    </div>
  </div>
</section>
<div class="tabs is-fullwidth is-boxed is-widescreen">
  <ul>
    <li><div>
    <a href="https://github.com/codemangasior" class="nav-item">
        <span class="icon">
            <i class="fa fa-github fa-2x"></i>
        <label class="label">codemangasior</label>
        </span>
    </a>
    </div></li>
    <li><div>
    <a href="mailto:lukasz.gasiorowski92@gmail.com" class="nav-item">
        <span class="icon">
            <i class="fa fa-at fa-2x"></i>
        <label class="label">codemangasior</label>
        </span>
    </a>
    </div></li>
  </ul>
</div>


<!-- Main container -->

<br>
    <div class="container">
        <div class="container">
            <div class="columns">
                <div class="column is-one-third">
                  <!--FORM-->

                    <form method="post">
                        {% csrf_token %}
                        <div class="box">
                            <label class="label">First name:</label><br>
                            <input class="input" name="first_name" placeholder="John" required>
                        </div>
                        <div class="box">
                            <label class="label">Last name:</label><br>
                            <input class="input" name="last_name" placeholder="Kowalsky" required>
                        </div>
                        <div class="box">
                            <label class="label">Profile photo:</label>
                            <uplyfile-uploader publickey="rekrutacjakey" name="profile_photo" accept="image/*" set-text-button="load picture"></uplyfile-uploader>
                        </div>
                        <div class="box">
                            <label class="label">CV</label>
                            <uplyfile-uploader publickey="rekrutacjakey" name="file" accept=".pdf" set-text-button="load CV"></uplyfile-uploader></p>
                        </div>
                        <div class="box">
                            <button class="button is-primary is-large is-fullwidth" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
                <div class="column">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
         </div>
    </div>
<footer class="footer">
    <div class="content has-text-centered">
    <p>
      <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. Everything else by codemangasior. All rights reserved.</a>
    </p>
    </div>
</footer>

<script src="https://uplycdn.com/widget/Yu922Xq6RDLZ/app.30a67353.js"></script>
  </body>
</html>

templates/welcome.html
{% extends 'do_pracy/index.html' %}

{% block welcome %}
        <p class="title is-5">Get start with button below</p>
        <a href="{% url 'do_pracy:index' %}">
            <div class="button is-primary is-large is-fullwidth">START</div>
        </a>
{% endblock %}